### ISSUE TITLE
fix(web): crypto.randomUUID crashes the workflow step editor on plain-HTTP LAN installs (insecure context)

### ISSUE THREAD

**Issue by joacominatel** [joacominatel/lazyit#1125]
## Symptom

On a self-hosted lazyit reached over **plain HTTP on a LAN IP** (the ADR-0087 deployment axis), opening the **step editor** in the Applications → Workflows builder throws:

```
TypeError: crypto.randomUUID is not a function
```

The workflow builder is unusable on those installs. Reported from a live production instance.

## Root cause

`crypto.randomUUID()` is **secure-context-only** (HTTPS or `localhost`). Over plain HTTP on an IP, `window.crypto` exists but `randomUUID` is `undefined`. Development never reproduces it because `localhost` *is* a secure context.

The calls were introduced by #946 / #970 ("stable per-row ids for React list keys"). React keys only need **local** uniqueness — a cryptographic UUID was never required.

## Affected call sites

| File | Lines |
| --- | --- |
| `apps/web/app/(app)/applications/[id]/workflows/_components/builder/step-editor.tsx` | 205, 299, 804, 814 |
| `apps/web/app/(app)/kb/_components/folder-access-rule-editor.tsx` | 52, 165 |

Lines 205 and 804 run inside a `useState` initializer, so the component throws **on mount** — not on interaction.

The KB folder-access-rule editor has the identical bug (not yet reported by a user).

## Fix

1. Replace all six calls with a monotonic module-local counter (`apps/web/lib/list-key.ts`) — no crypto, works in every context.
2. Add an ESLint `no-restricted-syntax` guard banning `crypto.randomUUID` / `crypto.subtle` in `apps/web` feature code, alongside the existing `no-raw-palette-colors` block. This is the **third** occurrence of the insecure-context class after #813 (`navigator.clipboard`).
3. Document the insecure-context browser-API constraint in ADR-0087.

## Out of scope (follow-up issue)

`apps/web/lib/secret-manager/totp.ts:87,95` uses `crypto.subtle` — also secure-context-only, so **TOTP secret items are non-functional on plain-HTTP installs**. Filed separately; it touches the INV-10 zero-knowledge path.

## Upgrade path

Pure frontend change, no migration, no data touched. Applies cleanly to any existing instance on update.
